### ISSUE TITLE
Processes worker fails once one company with Skip 'Clearinghouse SD Document' was onboarded

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-backend#1108]
### Current Behavior

Processes worker fails once one company with [Skip 'Clearinghouse Self Description Document'](https://github.com/eclipse-tractusx/portal/blob/portal-2.3.0-alpha.3/charts/portal/values.yaml#L68) was successfully onboarded, with the following error:

[19:49:41 ERR] processing failed with following Exception Value cannot be null. (Parameter 'Key')
System.ArgumentNullException: Value cannot be null. (Parameter 'Key')
   at System.Collections.Immutable.Requires.FailArgumentNullException(String parameterName)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)

### Expected Behavior

Processes worker doesn't fail

### Steps To Reproduce

Detected in 2.3.0-alpha.3

**Comment by MaximilianHauer** [comment]
@Phil91  / @evegufy  did you retest it already ?

**Comment by evegufy** [comment]
Yes, I retested it last month already
